name: Update Package Index

on:
  schedule:
    # Runs at 00:00 on the 1st of every month
    - cron: '0 0 1 * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./tools
        run: npm install

      - name: Generate the index
        run: node tools/create-index.mjs micropython-lib.yaml

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update micropython-lib.yaml index"
          file_pattern: 'micropython-lib.yaml'
