name: 'YAML Validation'
on:
  - pull_request
jobs:
  validate:
    name: 'Validate YAML'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Run Yamllint'
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: 'package-list.yaml'
          yamllint_strict: false
          yamllint_comment: true
          yamllint_config_filepath: 'yamllint-config.yml'
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Schema Validation'
        run: |
          npm i -g yaml-schema-validator
          schema validate -e -f package-list.yaml -s schema.yml